
class Constants:
      
    
    def getAmazonCSVColumns(self):
        a = [['item_sku', 'external_product_id', 'external_product_id_type', 'item_name', 'brand_name',
              'manufacturer', 'product_description',' item_type','feed_product_type', 'part_number', 'model', 'update_delete',
              'standard_price', 'currency', 'quantity', 'condition_type', 'condition_note', 'max_order_quantity',
              'sale_price', 'sale_from_date', 'sale_end_date', 'number_of_items', 'fulfillment_latency',
              'max_aggregate_ship_quantity', 'offering_can_be_gift_messaged', 'offering_can_be_giftwrapped',
              'product_site_launch_date', 'merchant_release_date', 'restock_date',
              'is_discontinued_by_manufacturer', 'missing_keyset_reason', 'product_tax_code', 'item_height',
              'item_length', 'item_width', 'item_dimensions_unit_of_measure', 'item_weight',
              'item_weight_unit_of_measure', 'website_shipping_weight', 'website_shipping_weight_unit_of_measure',
              'bullet_point1', 'bullet_point2', 'bullet_point3', 'bullet_point4', 'bullet_point5',
              'recommended_browse_nodes', 'generic_keywords1', 'generic_keywords2', 'generic_keywords3',
              'generic_keywords4', 'generic_keywords5', 'main_image_url', 'other_image_url1', 'other_image_url2',
              'other_image_url3', 'other_image_url4', 'other_image_url5', 'other_image_url6', 'other_image_url7',
              'other_image_url8', 'fulfillment_center_id', 'package_height', 'package_width', 'package_length',
              'package_dimensions_unit_of_measure', 'package_weight', 'package_weight_unit_of_measure',
              'country_of_origin', 'legal_disclaimer_description', 'safety_warning', 'included_components',
              'seller_warranty_description', 'special_features1', 'special_features2', 'special_features3',
              'special_features4', 'special_features5', 'color_name', 'color_map', 'material_composition',
              'material_type', 'form_factor', 'water_resistance_level', 'maximum_weight_capacity',
              'maximum_weight_capacity_unit_of_measure', 'compatible_devices', 'cable_length',
              'package_content_type', 'annual_energy_consumption', 'annual_energy_consumption_unit_of_measure',
              'specification_met1', 'specification_met2', 'specification_met3', 'specification_met4',
              'specification_met5', 'power_plug_type', 'battery_power', 'battery_cell_composition',
              'battery_average_life_recharge', 'refresh_rate_base', 'refresh_rate_unit_of_measure',
              'wireless_communication_technology1', 'wireless_communication_technology2',
              'wireless_communication_technology3', 'wireless_communication_technology4',
              'wireless_communication_technology5', 'finish_type', 'tuner_technology', 'built_in_decoders1',
              'built_in_decoders2', 'built_in_decoders3', 'built_in_decoders4', 'built_in_decoders5',
              'audio_output_effects', 'video_output_format', 'video_encoding', 'media_type_base1',
              'media_type_base2', 'media_type_base3', 'media_type_base4', 'media_type_base5', 'output_wattage',
              'software_included', 'supported_internet_services1', 'supported_internet_services2',
              'supported_internet_services3', 'supported_internet_services4', 'supported_internet_services5',
              'minimum_system_requirement_description', 'remote_control_description', 'human_interface_input1',
              'human_interface_input2', 'human_interface_input3', 'human_interface_input4',
              'human_interface_input5', 'parental_control_technology', 'compatible_mountings', 'audio_output_mode',
              'amplifier_type', 'surround_sound_channel_configuration', 'total_subwoofer_outputs',
              'number_of_radio_bands_supported', 'number_of_recording_loops', 'headphones_form_factor',
              'cable_length_unit_of_measure', 'connector_gender1', 'connector_gender2', 'connector_gender3',
              'connector_gender4', 'connector_gender5', 'coating_description', 'core_material_type',
              'total_power_outlets', 'effective_still_resolution', 'digital_zoom', 'optical_zoom',
              'min_shutter_speed', 'max_shutter_speed', 'continuous_shooting_speed', 'camera_film_speed',
              'camera_flash', 'flash_modes_description', 'flash_dedication', 'hot_shoe_included', 'guide_number',
              'focal_length_description', 'image_stabilization', 'viewfinder_type', 'photo_lens_thread_size',
              'photo_lens_thread_size_unit_of_measure', 'focus_type', 'lens_fixed_focal_length', 'min_focal_length',
              'max_focal_length', 'min_aperture', 'max_aperture', 'maximum_aperture_range',
              'photo_filter_effect_type', 'photo_filter_mount_type', 'photo_filter_bayonet_size',
              'photo_filter_drop_in_size', 'photo_filter_thread_size', 'photo_filter_thread_size_unit_of_measure',
              'video_capture_resolution', 'gps_navigation', 'map_type1', 'map_type2', 'map_type3', 'map_type4',
              'map_type5', 'traffic_features_description1', 'traffic_features_description2',
              'traffic_features_description3', 'traffic_features_description4', 'traffic_features_description5',
              'waypoints_type', 'blu_ray_region', 'dvd_region', 'dvd_type', 'battery_average_life_talk_time',
              'battery_average_life_talk_time_unit_of_measure', 'operating_system1', 'operating_system2',
              'operating_system3', 'operating_system4', 'operating_system5', 'number_of_handsets',
              'computer_memory_size', 'computer_memory_size_unit_of_measure', 'computer_cpu_manufacturer',
              'computer_cpu_speed', 'computer_cpu_speed_unit_of_measure', 'power_consumption',
              'power_consumption_unit_of_measure', 'efficiency', 'maximum_surge_rating',
              'maximum_surge_rating_unit_of_measure', 'power_source_type', 'voltage', 'wattage',
              'battery_average_life', 'battery_average_life_unit_of_measure', 'battery_type1', 'battery_type2',
              'battery_type3', 'lithium_battery_energy_content', 'lithium_battery_packaging',
              'lithium_battery_voltage', 'number_of_batteries1', 'number_of_batteries2', 'number_of_batteries3',
              'are_batteries_included', 'display_type', 'display_technology', 'display_size',
              'display_size_unit_of_measure', 'image_brightness', 'image_brightness_unit_of_measure',
              'image_contrast_ratio', '_3d_technology', 'screen_surface_description', 'aspect_ratio',
              'display_resolution_maximum', 'mounting_type', 'connectivity_technology', 'total_dvi_ports',
              'connector_type1', 'connector_type2', 'connector_type3', 'connector_type4', 'connector_type5',
              'total_vga_in_ports', 'total_component_in_ports', 'total_composite_ports', 'optical_digital_input',
              'total_hdmi_ports', 'total_preamp_outputs', 'total_s_video_out_ports', 'total_video_out_ports',
              'total_microphone_ports', 'total_firewire_ports', 'total_usb_ports', 'total_ethernet_ports',
              'total_coaxial_inputs', 'total_s_video_in_ports', 'speaker_count', 'speaker_type',
              'speaker_connectivity', 'impedance', 'impedance_unit_of_measure', 'speaker_maximum_input_power',
              'speaker_maximum_input_power_unit_of_measure', 'audio_sensitivity',
              'audio_sensitivity_unit_of_measure', 'tweeter_driver_diameter',
              'tweeter_driver_diameter_unit_of_measure', 'tweeter_driver_cone_material_type',
              'midrange_driver_diameter', 'midrange_driver_diameter_unit_of_measure',
              'midrange_driver_cone_material_type', 'woofer_driver_diameter',
              'woofer_driver_diameter_unit_of_measure', 'woofer_driver_cone_material_type', 'subwoofer_diameter',
              'subwoofer_diameter_unit_of_measure', 'subwoofer_cone_material_type', 'subwoofer_power_description',
              'subwoofer_amplifier_wattage', 'speaker_grille_material_type', 'speaker_grille_description',
              'item_shape', 'exterior_finish', 'flash_memory_installed_size',
              'flash_memory_installed_size_unit_of_measure', 'digital_storage_capacity',
              'digital_storage_capacity_unit_of_measure', 'removable_memory', 'memory_slots_available',
              'optical_sensor_resolution', 'optical_sensor_resolution_unit_of_measure']]
        return a

    def getFlipkartCSVColumns(self):
          a = [['Flipkart Serial Number',
                'QC Status', 'QC Failed Reason (if any)', 'Flipkart Product Link', 'Product Data Status',
                'Disapproval Reason (if any)', 'Seller SKU ID',
                'Brand', 'Model Number', 'Type	Color', 'Designed For	Material', 'Suitable Device',
                'Sales Package', 'Theme', 'Brand Color', 'Main Image URL',
                'Other Image URL 1', 'Other Image URL 2', 'Other Image URL 3', 'Other Image URL 4', 'EAN/UPC',
                'EAN/UPC - Measuring Unit', 'Pack of', 'Description',
                'Search Keywords', 'Key Spec 1', 'Key Spec 2', 'Key Spec 3', 'Key Spec 4', 'Key Features', 'Video URL',
                'Model Name', 'Cut Out Window',
                'Talk when Closed', 'Waterproof', 'Closure Type', 'Clip Type', 'Strap Included', 'Battery Indicator',
                'Access to Buttons', 'Additional Storage',
                'Finish', 'Design', 'Battery Capacity (mAh)', 'Battery Output', 'Width', 'Height', 'Depth (cm)',
                'Weight (g)', 'Other Dimensions', 'Certification',
                'Other Features', 'Domestic Warranty', 'Domestic Warranty - Measuring Unit', 'International Warranty',
                'International Warranty - Measuring Unit',
                'Warranty Summary', 'Warranty Service Type', 'Covered in Warranty', 'Not Covered in Warranty',
                'Supplier Image']]
          return a
    
    def get_amazon_csv_base1_row(self):
        return [["TemplateType=ConsumerElectronics","Version=2013.0903","The top 3 rows are for Amazon.com use only. Do not modify or delete the top 3 rows.","","","","","","","","","Offer - Offer Information - These attributes are required to make your item buyable for customers on the site","","","","","","","","","","","","","","","","","","","","Dimension - Product Dimensions - These attributes specify the size and weight of a product","","","","","","","","Discovery - Item Discovery Information - These attributes have an effect on how customers can find your product on the site using browse or search","","","","","","","","","","","Image - Image Information - These attributes provide links to images for a product","","","","","","","","","Fulfillment - Use these columns to provide fulfilment-related information for orders fulfilled either by Amazon (FBA) or by the seller.","","","","","","","Compliance - Compliance Information - Attributes used to comply with consumer laws in the country or region where the item is sold","","","Ungrouped - These attributes create rich product listings for your buyers.","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]]

    def get_amazon_csv_base2_row(self):
        return [['Seller SKU','Product ID','Product ID Type','Item Title','Brand Name','Manufacturer','Product Description','Item Type','Product Type','Manufacturer Part Number','Model Number','Update Delete','Standard Price','Quantity','Item Condition','Item Condition Note','Max Order Quantity','Sale Price','Sale Start Date','Sale End Date','Number of Items','Fulfillment Latency','Maximum Aggregate Ship Quantity','Can Be Gift Messaged','Is Gift Wrap Available?','Launch Date','Release Date','Restock Date','Is Discontinued By Manufacturer','Product Tax Code','Shipping-Template','Item Height','Item Length','Item Width','Item Dimensions Unit Of Measure','Item Weight Unit of Measure','Item Weight Unit Of Measure','Shipping Weight','Website Shipping Weight Unit Of Measure','Product Attributes Bullet Points1','Product Attributes Bullet Points2','Product Attributes Bullet Points3','Product Attributes Bullet Points4','Product Attributes Bullet Points5','Recommended Browse Node','Search Terms','Main Image URL','Other Image URL1','Other Image URL2','Other Image URL3','Fulfillment Center ID','Package Height','Package Width','Package Length','Package Dimensions Unit Of Measure','Package Weight','Package Weight Unit Of Measure','Country of Origin','Legal Disclaimer','Safety Warnings','Box Contents','Product Features1','Product Features2','Product Features3','Product Features4','Product Features5','Colour','Colour Map','Enclosure Material','Form Factor','Compatible Devices','Amplifier Type','Package Content Type','Operating Systems','Wattage','Battery Cell Type','Lithium Battery Packaging','Lithium Battery Voltage','BatteryType','Number of Batteries','Are Batteries Included?','Screen Size Unit Of Measure','Display Size Unit Of Measure','Maximum Display Resolution','Network Connectivity Technology','Speaker Type','Speaker Connectivity','Digital Storage Capacity Unit Of Measure','Digital Storage Capacity Unit Of Measure','Compatible Mountings','Lens Type','Photo Filter Thread Size Unit Of Measure','Photo Filter Thread Size Unit Of Measure','Wireless Technology','Number of Audio Channels','Effective Still Resolution','conductor','Optical Zoom','Image Stabilization Type','Viewfinder Type','Maximum Focal Length Unit Of Measure','Display Technology','Minimum Focal Length','Ram Size','Computer Memory Size Unit Of Measure','Processor Brand','Processor Speed','Computer CPU Speed Unit Of Measure','VESA Mount Type','Analog Rgb Input','optical_sensor_resolution_unit_of_measure','optical_sensor_resolution']]

    def get_amazon_csv_base3_row(self):
        return [['item_sku','external_product_id','external_product_id_type','item_name','brand_name','manufacturer','product_description','item_type','feed_product_type','part_number','model','update_delete','standard_price','quantity','condition_type','condition_note','max_order_quantity','sale_price','sale_from_date','sale_end_date','number_of_items','fulfillment_latency','max_aggregate_ship_quantity','offering_can_be_gift_messaged','offering_can_be_giftwrapped','product_site_launch_date','merchant_release_date','restock_date','is_discontinued_by_manufacturer','product_tax_code','merchant_shipping_group_name','item_height','item_length','item_width','item_dimensions_unit_of_measure','item_weight','item_weight_unit_of_measure','website_shipping_weight','website_shipping_weight_unit_of_measure','bullet_point1','bullet_point2','bullet_point3','bullet_point4','bullet_point5','recommended_browse_nodes','generic_keywords','main_image_url','other_image_url1','other_image_url2','other_image_url3','fulfillment_center_id','package_height','package_width','package_length','package_dimensions_unit_of_measure','package_weight','package_weight_unit_of_measure','country_of_origin','legal_disclaimer_description','safety_warning','included_components','special_features1','special_features2','special_features3','special_features4','special_features5','color_name','color_map','material_type','form_factor','compatible_devices','amplifier_type','package_content_type','operating_system','wattage','battery_cell_composition','lithium_battery_packaging','lithium_battery_voltage','battery_type','number_of_batteries','are_batteries_included','display_size','display_size_unit_of_measure','display_resolution_maximum','connectivity_technology','speaker_type','speaker_connectivity','digital_storage_capacity','digital_storage_capacity_unit_of_measure','compatible_mountings','focal_length_description','photo_filter_thread_size','photo_filter_thread_size_unit_of_measure','wireless_communication_technology','surround_sound_channel_configuration','effective_still_resolution','core_material_type','optical_zoom','image_stabilization','viewfinder_type','max_focal_length','display_technology','min_focal_length','computer_memory_size','computer_memory_size_unit_of_measure','computer_cpu_manufacturer','computer_cpu_speed','computer_cpu_speed_unit_of_measure','mounting_type','connector_type','optical_sensor_resolution_unit_of_measure','optical_sensor_resolution']]
        
